// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Website.ModelsFromPowerTools;

public partial class DB_126687_mainContext : DbContext
{
    public DB_126687_mainContext(DbContextOptions<DB_126687_mainContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Group> Groups { get; set; }

    public virtual DbSet<Job> Jobs { get; set; }

    public virtual DbSet<JobDetail> JobDetails { get; set; }

    public virtual DbSet<JobResumeLine> JobResumeLines { get; set; }

    public virtual DbSet<JobSkill> JobSkills { get; set; }

    public virtual DbSet<Person> People { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Group>(entity =>
        {
            entity.ToTable("Group");

            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Job>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Job$PrimaryKey");

            entity.ToTable("Job");

            entity.Property(e => e.Company).HasMaxLength(255);
            entity.Property(e => e.Dates).HasMaxLength(255);
            entity.Property(e => e.EndDate).HasMaxLength(255);
            entity.Property(e => e.Location).HasMaxLength(255);
            entity.Property(e => e.Role).HasMaxLength(255);
            entity.Property(e => e.StartDate).HasMaxLength(255);
        });

        modelBuilder.Entity<JobDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("JobDetail$PrimaryKey");

            entity.ToTable("JobDetail");

            entity.HasMany(d => d.JobSkills).WithMany(p => p.JobDetails)
                .UsingEntity<Dictionary<string, object>>(
                    "JobDetailJobSkill",
                    r => r.HasOne<JobSkill>().WithMany()
                        .HasForeignKey("JobSkillId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("JobDetailSkill$JobSkillJobDetailJobSkill"),
                    l => l.HasOne<JobDetail>().WithMany()
                        .HasForeignKey("JobDetailId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("JobDetailSkill$JobDetailJobDetailJobSkill"),
                    j =>
                    {
                        j.HasKey("JobDetailId", "JobSkillId").HasName("JobDetailSkill$PrimaryKey");
                        j.ToTable("JobDetailJobSkill");
                        j.HasIndex(new[] { "JobSkillId" }, "JobDetailSkill$JobSkillId");
                    });
        });

        modelBuilder.Entity<JobResumeLine>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("JobResumeLine");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.Purpose).HasMaxLength(255);
            entity.Property(e => e.Style).HasMaxLength(255);
        });

        modelBuilder.Entity<JobSkill>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("JobSkill$PrimaryKey");

            entity.ToTable("JobSkill");

            entity.Property(e => e.Comments).HasMaxLength(100);
            entity.Property(e => e.Count).HasDefaultValue(0);
            entity.Property(e => e.Title).HasMaxLength(50);
        });

        modelBuilder.Entity<Person>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Person__3214EC0763636528");

            entity.ToTable("Person");

            entity.Property(e => e.Company).HasMaxLength(100);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ImageFilename).HasMaxLength(100);
            entity.Property(e => e.LastName).HasMaxLength(50);
            entity.Property(e => e.Phone).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}