// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Website.ModelsFromPowerTools;

public partial class Job
{
    public int Id { get; set; }

    public string Company { get; set; }

    public string Location { get; set; }

    public string Dates { get; set; }

    public string StartDate { get; set; }

    public string EndDate { get; set; }

    public string Role { get; set; }
}