// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Website.ModelsFromPowerTools;

public partial class JobDetail
{
    public int Id { get; set; }

    public int? JobId { get; set; }

    public int? Sequence { get; set; }

    public string Description { get; set; }

    public virtual ICollection<JobSkill> JobSkills { get; set; } = new List<JobSkill>();
}