// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Website.ModelsFromPowerTools;

public partial class JobResumeLine
{
    public int Id { get; set; }

    public int? Sequence { get; set; }

    public string Style { get; set; }

    public string Purpose { get; set; }

    public string Details { get; set; }
}