// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Website.ModelsFromPowerTools;

public partial class JobSkill
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int? Count { get; set; }

    public string Comments { get; set; }

    public string Summary { get; set; }

    public virtual ICollection<JobDetail> JobDetails { get; set; } = new List<JobDetail>();
}